config/routes.rb
Summers::Application.routes.draw do
  resources :articles, :only => [:index, :show]
  resources :tickets

  match "/admin/createAdmin" => "admin#createAdmin", :via => :post
  match "/admin/loginCheck" => "admin#loginCheck", :via => :post
  match "/admin/update" => "admin#update", :via => :put

  match "/contact.html" => 'tickets#new'

  namespace :admin do
    get "log_in", "log_out", "edit"
    get '/' => 'tickets#index'
    
    resources :tickets
    resources :articles, :except => :new do
      match 'uploadPhoto' => 'articles#createPhoto', :via => [:post]
      match 'deletePhoto/:id' => 'articles#destroyPhoto', :via => [:delete]
    end
  end

end

app/models/article.rb
#encoding: utf-8
class Article < ActiveRecord::Base
  attr_accessible :content, :count, :metakw, :namehash, :title, :status, :publishDate
  has_many :articlephotos, :dependent => :destroy
  validates :namehash, :uniqueness => { :message => "網址重複，請重新輸入。" }, :allow_nil => true, :allow_blank => true
  validates :namehash, :format => { :with => /^[^(.\s)]?[^(.\s)]*[^(.\s)]?$/, :message => "網址不能包含空白字元或.(dot)，請重新輸入。" }, :if => :not_blank?

  validates :title, :content, :metakw, :presence =>{:message => "不能為空"}, :if => :is_article?

  before_save :stamp_publishDate

  def not_blank?
    (namehash && namehash.length >0)
  end

  def is_article?
    status == "article"
  end

  def stamp_publishDate
    if(self.publishDate.blank?)
      self.publishDate = DateTime.now
    end
  end

  paginates_per 15
  
  #delete the blank folder built by carrierwave
  before_destroy :remember_id
  after_destroy :remove_id_directory

  

  protected
  def remember_id
    @id = id
  end

  def remove_id_directory
    FileUtils.remove_dir("#{Rails.root}/public/uploads/Articlephoto/#{@id}", :force => true)
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_filter :require_is_admin
  layout 'admin'

  def index
    @articles = Article.order("publishDate DESC, created_at DESC").page(params[:page])

    respond_to do |format|
      format.html
      format.json { render json: @articles }
    end
  end

  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @article }
    end
  end

  def edit
    @article = Article.find(params[:id])
    @photo = Articlephoto.new
  end

  def create
    @article = Article.new

    respond_to do |format|
      if @article.save
        format.html { redirect_to edit_admin_article_path(@article), notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { redirect_to admin_articles_path }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @article = Article.find(params[:id])
    
    if(params[:article_show])
      @article.status = "show"
    else
      @article.status = ""
    end

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to admin_article_path(@article), notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        @photo = Articlephoto.new
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to admin_articles_path }
      format.json { head :no_content }
    end
  end

  def createPhoto
    @photo = Article.find(params[:article_id]).articlephotos.new(params[:articlephoto])

    respond_to do |format|
      if @photo.save
        format.json { render json: @photo, status: :created, location: @photo }
        format.js
      else
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroyPhoto
    @photo = Articlephoto.find(params[:id])
    @photopath = "public/uploads/Articlephoto/"+ @photo.article_id.to_s + "/" + @photo.id.to_s + "-" + @photo.name
    
    if(File.exist?(@photopath))
      File.delete(@photopath)
    end

    @photo.destroy

    respond_to do |format|
      format.html { redirect_to :controller => 'photos', :action => 'index' }
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    @articles = Article.where("status = ?", "article").order("publishDate DESC, created_at DESC").all

    if(@articles)
      @articles.each do | article |
        if(!article.content.blank?)
          @paragraphs = JSON.parse(article.content)
          @paragraphs.each do | p |
            next if p["type"] != "img"

            article[:imgpath] = p["path"]
            break
          end
        end
      end
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  def show
    @article = Article.where("(id = ? or namehash = ?) and status = ?", params[:id], params[:id], "article").first

    if(@article)
      #find prev and next article
      @prev = Article.where("publishDate > ? and status = ?", @article.publishDate, "article").order("publishDate DESC, created_at DESC").last
      if(!@prev)
        @prev = Article.where("status = ?", "article").order("publishDate DESC, created_at DESC").last
      end

      @next = Article.where("publishDate < ? and status = ?", @article.publishDate, "article").order("publishDate DESC, created_at DESC").first
      if(!@next)
        @next = Article.where("status = ?", "article").order("publishDate DESC, created_at DESC").first
      end

      # generate contents for meta tags
      $meta_description = '';
      if(!@article.content.blank?)
        @paragraphs = JSON.parse(@article.content)
        max_length = 100

        @paragraphs.each do | p |
          if p["type"] == "p"

          partical_content = p["content"].gsub(/\\n/, "")
          $meta_description += partical_content
          max_length -= partical_content.length

          break if max_length <= 0
          
          elsif p["type"] == "img" && !@article[:imgpath]
            @article[:imgpath] = p["path"]

          else
            next
          end

        end
      end
      
      $meta_kw = @article.metakw

      # article click count
      @article.count += 1
      @article.save
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<!doctype html>
<html>
<head>
<!--[if lt IE 9]>
<script src="js/html5.js"></script>
<link rel="stylesheet" href="/css/style-article.css">
<link rel="stylesheet" href="/assets/front/article/wide">
<![endif]-->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
<meta name="Robots" content="index,follow"/>
<meta http-equiv="content-language" content="zh-TW" />

<meta name="keywords" content="網頁設計, 網站設計, 設計網頁, 設計網站"/>
<meta name="description" content="無私奉送網站工作隨筆記，搜羅網站設計產業資訊，分析網頁設計重要趨勢，實戰網路行銷操作經驗分享。略過迢迢冤枉路，製作網站前，一定要參考的經驗談！瞄準網路商機的最佳參考指南—網站工作隨筆。"/>

<meta property="og:title" content="網站工作隨筆×當代網頁設計觀點"/>
<meta property="og:description" content="無私奉送網站工作隨筆記，搜羅網站設計產業資訊，分析網頁設計重要趨勢，實戰網路行銷操作經驗分享。略過迢迢冤枉路，製作網站前，一定要參考的經驗談！瞄準網路商機的最佳參考指南—網站工作隨筆。"/>
<meta property="og:site_name" content="夏天廣告官方網站"/>
<meta property="og:type" content="company"/>
<meta property="og:image" content="/images/thumbnail.jpg"/>

<meta name="msvalidate.01" content="BD7CCAECD53F3EDDF89A9F154C15F65E" />
<link rel="image_src" href="/images/thumbnail.jpg"/>
<title>網站工作隨筆×當代網頁設計觀點</title>
<link rel="shortcut icon" href="/images/favicon.ico" >
<%= stylesheet_link_tag "article" %>
<link rel="stylesheet" media="screen and (max-width: 581px)" href="/assets/front/article/narrow" />
<link rel="stylesheet" media="screen and (min-width: 582px) and (max-width: 1023px)" href="/assets/front/article/medium" />
<link rel="stylesheet" media="screen and (min-width: 1024px)" href="/assets/front/article/wide" />
<script src="/js/jquery-1.8.1.min.js"></script>
<script src="/js/jquery.easing.1.3.js"></script>
<script src="/assets/front"></script>
<script>
  jQuery(document).ready(function(){
    $("body").css("display", "none");
    $("body").fadeIn(500);
    $("nav a").click(function(event){
        event.preventDefault();
        linkLocation = this.href;
        $("body").fadeOut(500, redirectPage);
    });     
    function redirectPage() {
        window.location = linkLocation;
    }
    
    $(".title a").hover(function(){
        $(this).children("h4").stop().animate({height:60},400,'easeInOutBack')
    },function(){
        $(this).children("h4").stop().animate({height:50},400,'easeInOutBack')  
    });
});
</script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22983915-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38776205-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?488af24fc55cb9a4eeac7da38383e935";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
</head>

<body>
<header> 
  <nav itemscope itemtype="http://data-vocabulary.org/Breadcrumb"> 
  <span id="ctrl"><img src="/images/article/ctrl.png"></span>
  <a href="../contact.html" itemprop="url"  title="業務聯絡"><span itemprop="title">業務聯絡</span></a> <span class="star">★</span> <a href="../works/enterprise.html" itemprop="url"><span itemprop="title" title="作品">作品</span></a> <span class="star">★</span> <a href="../service.html" itemprop="url" title="服務項目"><span itemprop="title">服務項目</span></a> <span class="star">★</span> <a href="/articles" itemprop="url" title="網站工作隨筆"><span itemprop="title">網站工作隨筆</span></a></nav>
  <div id="cloud"> </div>
  <aside _height="none"> <a href="http://www.summers.com.tw" title="夏天廣告 | 網頁設計觀點">夏天廣告</a> </aside>
</header>
<article>
  <section class="limit" >
    <h2><a href="<%= articles_path %>">網站工作隨筆</a></h2>
    <% @articles.each do |article| %>
    <div class="content list">
      <div class="publish">
        <span class="date"><%= article.publishDate.strftime("%m/%d") if(article.publishDate) %></span><br>
        <span class="year"><%= article.publishDate.strftime("%Y") if(article.publishDate) %></span>
      </div>
      <!--publish-->
      <div class="title">
        <% if(article.namehash.empty?) %>
        <a href="<%= article_path(article) %>">
          <% else %>
          <a href="<%= article_path(article.namehash) %>">
            <% end %>
            <img src="<%= article["imgpath"] ? article.imgpath : "/images/article/error.jpg" %>">
            <h4><%= article.title %></h4>
          </a>
        </div>
        <!--title-->
    </div>
    <% end %>

    </section>
  <!--limit--> 
</article>
<div id="forest"></div>
<footer>
  <section class="limit">
    <div class="flt">
      <div id="contact"><a href="../contact.html">業務聯絡 <span>></span></a></div>
      <div id="logo"><a href="http://www.summers.com.tw" title="夏天廣告 | 網頁設計觀點"></a></div>
      <div id="gplus">Copyright © <a href="https://plus.google.com/109325166536931705977?rel=author" target="_blank">Summers</a></div>
    </div>
    <!--flt--> 
  </section>
  <!--limit--> 
</footer>
</body>
</html>

app/views/articles/show.html.erb
<!doctype html>
<html>
<head>
<!--[if lt IE 9]>
<script src="/js/html5.js"></script>
<link rel="stylesheet" href="/css/style-article.css">
<link rel="stylesheet" href="/assets/front/article/wide">
<![endif]-->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
<meta name="Robots" content="index,follow"/>
<meta http-equiv="content-language" content="zh-TW" />

<meta name="keywords" content="<%= $meta_kw %>"/>
<meta name="description" content="<%= $meta_description %>"/>

<meta property="og:title" content="<%= @article.title %>-網站工作隨筆"/>
<meta property="og:description" content="<%= $meta_description %>"/>
<meta property="og:site_name" content="夏天廣告官方網站"/>
<meta property="og:type" content="company"/>
<meta property="og:image" content="http://www.summers.com.tw<%= @article["imgpath"] ? @article.imgpath : "/images/thumbnail.jpg" %>"/>

<meta name="msvalidate.01" content="BD7CCAECD53F3EDDF89A9F154C15F65E" />
<link rel="image_src" href="/images/thumbnail.jpg"/>

<title><%= @article.title %>-網站工作隨筆</title>
<link rel="shortcut icon" href="/images/favicon.ico" >
<%= stylesheet_link_tag "article" %>
<link rel="stylesheet" media="screen and (max-width: 581px)" href="/assets/front/article/narrow" />
<link rel="stylesheet" media="screen and (min-width: 582px) and (max-width: 1023px)" href="/assets/front/article/medium" />
<link rel="stylesheet" media="screen and (min-width: 1024px)" href="/assets/front/article/wide" />
<script src="/js/jquery-1.8.1.min.js"></script>
<script src="/js/jquery.easing.1.3.js"></script>
<script src="/assets/front"></script>

<link rel="stylesheet" type="text/css" href="/peditor/css/peditor.css">
<script src="/peditor/js/editor.js"></script>
<script src="/peditor/js/editor_p.js"></script>
<script src="/peditor/js/editor_img.js"></script>
<script src="/peditor/js/editor_list.js"></script>
<script src="/peditor/js/editor_video.js"></script>

<script>
  jQuery(document).ready(function(){
  $("body").css("display", "none");
    $("body").fadeIn(500);
  $("nav a").click(function(event){
        event.preventDefault();
        linkLocation = this.href;
        $("body").fadeOut(500, redirectPage);
    });   
    function redirectPage() {
        window.location = linkLocation;
    }
  
  $(".title a").hover(function(){
    $(this).children("h3").stop().animate({height:70},400,'easeInOutBack')
  },function(){
    $(this).children("h3").stop().animate({height:50},400,'easeInOutBack')  
  });
});
</script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-22983915-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38776205-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?488af24fc55cb9a4eeac7da38383e935";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
</head>

<body>
<header>
  <nav itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
    <span id="ctrl"><img src="/images/article/ctrl.png"></span>
    <a href="../contact.html" itemprop="url"  title="業務聯絡"><span itemprop="title">業務聯絡</span></a> <span class="star">★</span> <a href="../works/enterprise.html" itemprop="url"><span itemprop="title" title="作品">作品</span></a> <span class="star">★</span> <a href="../service.html" itemprop="url" title="服務項目"><span itemprop="title">服務項目</span></a> <span class="star">★</span> <a href="/articles" itemprop="url" title="網站工作隨筆"><span itemprop="title">網站工作隨筆</span></a>
  </nav>
  <div id="cloud"> </div>
</header>
<article>
  <section class="limit" >
    <h2><a href="<%= articles_path %>">網站工作隨筆</a></h2>
    <div class="content single">
      <% if(@article) %>
      <h3><%= @article.title %></h3>
      <div class="banner">
        <div class="publish"> 
          <div class="day"><%= @article.publishDate.strftime("%d") if(@article.publishDate) %></div>
          <div class="month"><%= @article.publishDate.strftime("%B").slice(0, 3) if(@article.publishDate) %></div> 
        </div>
        <!--publish-->
      </div>
      <!--banner-->

      <input id="article_content" style="display:none;" type="text" value="<%=@article.content%>">
      <div class="inner" id="articleContent"></div>
      <!--inner-->

      <% else %>
      <h3>該篇文章不存在，請返回短文列表。</h3>
      <% end %>
    </div>

    <div class="social">
      <!-- FB -->
      <iframe src="//www.facebook.com/plugins/like.php?href=<%= "#{request.protocol}#{request.host_with_port}#{request.fullpath}" %>&amp;send=false&amp;layout=box_count&amp;width=100&amp;show_faces=false&amp;font&amp;colorscheme=light&amp;action=like&amp;height=90&amp;appId=433197170080910" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:50px; height:60px;" allowTransparency="true"></iframe>

      <!-- Google+ +1 -->
      <div class="g-plusone" data-size="tall"></div>
    </div>

    <!-- js for Google+ -->
    <script type="text/javascript">
    window.___gcfg = {lang: 'zh-TW'};

    (function() {
      var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
      po.src = 'https://apis.google.com/js/plusone.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
    })();
    </script>

    <div id="page">
      <% if(@prev) %>
      <a href="<%= article_path((@prev.namehash.length > 0)? @prev.namehash : @prev.id) %>" class="prev" title="<%= @prev.title%>">Prev</a>
      <% end %>

      <a href="<%= articles_path %>" class="more" title="回文章列表">..看更多..</a>

      <% if(@next) %>
      <a href="<%= article_path((@next.namehash.length > 0)? @next.namehash : @next.id) %>" class="next" title="<%= @next.title%>">Next</a>
      <% end %>

    </div>
  </section>
  <!--limit-->
</article>
<div id="forest"></div>
<footer>
  <section class="limit">
    <div class="flt">
      <div id="contact"><a href="../contact.html">業務聯絡 <span>></span></a></div>
      <div id="logo"><a href="http://www.summers.com.tw" title="夏天廣告 | 網頁設計觀點"></a></div>
      <div id="gplus">Copyright © <a href="https://plus.google.com/109325166536931705977?rel=author" target="_blank">Summers</a></div>
    </div>
    <!--flt--> 
  </section>
  <!--limit--> 
</footer>
</body>
</html>

<script type="text/javascript">
$(document).ready(function(){
  <% if(@article) %>
  editor.output();

  if($("div[data-type=img]").length>0)
  {
    $("div[data-type=img]:first").children("img").attr("alt", "<%= @article.title %>").attr("title", "<%= @article.title %>");
    $("div.banner").append($("div[data-type=img]:first").children("img"));
    $("div[data-type=img]:first").remove();
  }
  else
  {
    $("div.banner").append($("<img>").attr("alt", "<%= @article.title %>").attr("title", "<%= @article.title %>").attr("src", "/images/article/error.jpg"));
  }

  $("#articleContent").children("div").each(function(){
    $("#articleContent").append($(this).html());
    $(this).remove();
  });
  <% else %>
  window.location.assign("/404");
  <% end %>
});
</script>