config/routes.rb
Summers::Application.routes.draw do
  resources :articles, :only => [:index, :show]
  resources :tickets

  match "/admin/createAdmin" => "admin#createAdmin", :via => :post
  match "/admin/loginCheck" => "admin#loginCheck", :via => :post
  match "/admin/update" => "admin#update", :via => :put

  match "/contact.html" => 'tickets#new'

  namespace :admin do
    get "log_in", "log_out", "edit"
    get '/' => 'tickets#index'
    
    resources :tickets
    resources :articles, :except => :new do
      match 'uploadPhoto' => 'articles#createPhoto', :via => [:post]
      match 'deletePhoto/:id' => 'articles#destroyPhoto', :via => [:delete]
    end
  end

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :content, :email, :issue, :name, :phone
  
  paginates_per 15
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < ApplicationController

  before_filter :require_is_admin
  layout 'admin'

  # GET /tickets
  # GET /tickets.json
  def index
	  @tickets = Ticket.order('created_at DESC').page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to admin_tickets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

	layout false

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # POST /tickets
  # POST /tickets.json
  def create
  
    @ticket = Ticket.new( params[:ticket] )
     
    respond_to do |format|
      if @ticket.save
      
        TicketMailer.send_notice(@ticket).deliver
      
        #format.html { redirect_to :action => :new, :anchor => "finished" }
        format.html { redirect_to "/contact.html#finished" }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/tickets/index.html.erb
<article>
  <section class="list">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th align="left" class="x0 x2">詢問日期</th>
        <th align="left">客戶姓名</th>
        <th align="left" class="x1">刪除</th>
      </tr>
      <% @tickets.each do |ticket| %>
      <tr>
        <td class="x0"><%= ticket.created_at.strftime("%Y-%m-%d") %></td>
        <td><a href="msg-show.html"><%= link_to ticket.name, admin_ticket_path(ticket) %></a></td>
        <td class="delete">
          <%= link_to image_tag("/images/delete.png"), admin_ticket_path(ticket), method: :delete, data: { confirm: '確定刪除消息?' } %>
        </td>
      </tr>
      <% end %>
    </table>
  </section>
  <!--list-->
  <%= paginate @tickets, :theme => 'admin' %>
  <!--page-->
</article>

<script type="text/javascript">
$(document).ready(function(){
  $("#nav-1").parents("li").addClass("active");
});
</script>

app/views/admin/tickets/show.html.erb
<article>
  <section class="title">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <th><%= @ticket.created_at.strftime("%Y-%m-%d") %></th>
        <td><%= @ticket.name %></td>
      </tr>
    </table>
  </section>
  <!--title-->
  <section class="text text-show">
    <div class="one">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <th valign="top">電話：</th>
          <td><%= @ticket.phone %></td>
        </tr>
      </table>
    </div>

    <div class="one">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <th valign="top">郵件：</th>
          <td><%= @ticket.email %></td>
        </tr>
      </table>
    </div>
    <div class="one">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <th valign="top">需求：</th>
          <td><%=(@ticket.issue && @ticket.issue.length>0) ?  @ticket.issue : "<其他>" %></td>
        </tr>
      </table>
    </div>
    <div class="one">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <th>其他：</th>
          <td><%= (@ticket.content.length>0) ? @ticket.content : "<空>" %></td>
        </tr>
      </table>
    </div>
  </section>
  <!--text-->
  <section class="button">
  <%= link_to image_tag("/images/back_icon.png")+'返回', admin_tickets_path %>
  </section>
  <!--button-->
</article>

<script type="text/javascript">
$(document).ready(function(){
  $("#nav-1").parents("li").addClass("active");
});
</script>